### ISSUE TITLE
开源协议是？

### ISSUE THREAD

**Issue by messense** [jacksyen/gk7-douban#1]
你好，我基于你的这个版本的 idea 和代码，用 Django、Celery 写了一个自用。代码在：

https://github.com/messense/douban2kindle

请问一下，你的代码的开源协议是哪个？谢谢！

**Comment by jacksyen** [comment]
开源协议是 GPL v2，我这就给项目license加上

在 2015年1月2日 下午1:21，messense <notifications@github.com>写道：

> 你好，我基于你的这个版本的 idea 和代码，用 Django、Celery 写了一个自用。代码在：
>
> https://github.com/messense/douban2kindle
>
> 请问一下，你的代码的开源协议是哪个？谢谢！
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacksyen/gk7-douban/issues/1>.
>



-- 
-----
Regards, Jack Syen
Home:  http://blog.gk7.pw
GitHub: https://github.com/jacksyen
E-Mail: hyqiu.syen@gmail.com
Mobile: +86 13983479195

**Comment by messense** [comment]
谢谢告知，已改为 GPL v2 协议。
