### ISSUE TITLE
图片变得不清晰

### ISSUE THREAD

**Issue by yuchen-lea** [jacksyen/gk7-douban#10]
感谢您的工具！现在的问题是推送后生的epub中的图片变得模糊

这是douban阅读中的：
<img width="837" alt="图片" src="https://github.com/jacksyen/gk7-douban/assets/7555085/12b10ab9-c944-490e-905a-0864f1504211">

这是下载下来的：
<img width="540" alt="图片" src="https://github.com/jacksyen/gk7-douban/assets/7555085/37aaa6f0-4e65-4db0-a186-b46788cabcf2">

https://read.douban.com/reader/ebook/447759076/?dcs=bookshelf

**Comment by yuchen-lea** [comment]
<img width="2287" alt="图片" src="https://github.com/jacksyen/gk7-douban/assets/7555085/2bca145a-5975-40b5-85d1-b8e87066a5ae">

**Comment by jacksyen** [comment]
以前也有使用者提出过这个问题，因为有的书籍中图片非常多，导致转换成epub格式后文件很大，而发送邮件的大小是有限制的，故而等比例裁减为较小的尺寸，现在服务器已经调整为宽度为760，高度等比例缩放

**Comment by yuchen-lea** [comment]
那能不能直接本地下载，不需要通过发送邮件？
