### ISSUE TITLE
下标处理异常

### ISSUE THREAD

**Issue by yuchen-lea** [jacksyen/gk7-douban#11]
<img width="578" alt="图片" src="https://github.com/jacksyen/gk7-douban/assets/7555085/1eee2d2c-2dbb-47ee-bc0c-4ca04d9daa29">

下载后

<img width="656" alt="图片" src="https://github.com/jacksyen/gk7-douban/assets/7555085/2f87c23a-84ca-4d26-86c6-06368d748691">

**Comment by jacksyen** [comment]
产生这样的问题是因为数据公式需要基于Latex来显示，html中有第三方插件可以支持，而epub不支持外部样式。
现在插件已经使用另外一种方式（图片转换）做了适配

**Comment by yuchen-lea** [comment]
我可以选择不用图片转换么？简单的公式用sub和sup标签自己处理就可以了
