### ISSUE TITLE
代码片段丢失

### ISSUE THREAD

**Issue by messense** [jacksyen/gk7-douban#2]
生成 HTML 的时候没有处理 type=code 的部分，导致计算机类书籍代码片段丢失。

See [https://github.com/messense/douban2kindle/commit/ff1655d3b982fdc8c06447b4ff1e6d2b8279fe91](https://github.com/messense/douban2kindle/commit/ff1655d3b982fdc8c06447b4ff1e6d2b8279fe91)

**Comment by jacksyen** [comment]
谢谢，code这块我还没发现，暂时知道还少了type='emphasize'片段，测试的书籍不够，不知道豆瓣到底有多少种类型，只能后期慢慢优化

2015-01-04 19:17 GMT+08:00 messense <notifications@github.com>:

> 生成 HTML 的时候没有处理 type=code 的部分，导致计算机类书籍代码片段丢失。
>
> See messense/douban2kindle@ff1655d
> <https://github.com/messense/douban2kindle/commit/ff1655d3b982fdc8c06447b4ff1e6d2b8279fe91>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacksyen/gk7-douban/issues/2>.
>



-- 
-----
Regards, Jack Syen
Home:  http://blog.gk7.pw
GitHub: https://github.com/jacksyen
E-Mail: hyqiu.syen@gmail.com
Mobile: +86 13983479195

**Comment by jacksyen** [comment]
我说错了，不是type少了'emphasize'，还是详见代码吧，
https://github.com/jacksyen/gk7-douban/commit/7bd9ab6bb1dbaef9aa549e2c54b9d4921a471b75#diff-f22e4e33767f2696559b41aab146552a

在 2015年1月4日 下午9:24，Jack Syen <hyqiu.syen@gmail.com>写道：

> 谢谢，code这块我还没发现，暂时知道还少了type='emphasize'片段，测试的书籍不够，不知道豆瓣到底有多少种类型，只能后期慢慢优化
>
> 2015-01-04 19:17 GMT+08:00 messense <notifications@github.com>:
>
>> 生成 HTML 的时候没有处理 type=code 的部分，导致计算机类书籍代码片段丢失。
>>
>> See messense/douban2kindle@ff1655d
>> <https://github.com/messense/douban2kindle/commit/ff1655d3b982fdc8c06447b4ff1e6d2b8279fe91>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jacksyen/gk7-douban/issues/2>.
>>
>
>
>
> --
> -----
> Regards, Jack Syen
> Home:  http://blog.gk7.pw
> GitHub: https://github.com/jacksyen
> E-Mail: hyqiu.syen@gmail.com
> Mobile: +86 13983479195
>



-- 
-----
Regards, Jack Syen
Home:  http://blog.gk7.pw
GitHub: https://github.com/jacksyen
E-Mail: hyqiu.syen@gmail.com
Mobile: +86 13983479195

**Comment by jacksyen** [comment]
已发布新版本(v2.4.2)修复，另外考虑未知的type元素太多，将未知的信息写入日志，以便后期优化
